# Generated by Django 2.0.6 on 2018-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_orders_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
