# Generated by Django 2.0.6 on 2018-06-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0004_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='payment_status',
        ),
    ]
