# Generated by Django 2.0.6 on 2018-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0006_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_boy',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
