# Generated by Django 2.0.6 on 2018-06-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0009_auto_20180628_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='money_recieved',
            new_name='money_received',
        ),
    ]
