# Generated by Django 2.0.6 on 2018-07-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0012_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='balance',
        ),
    ]
