# Generated by Django 2.0.6 on 2018-07-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0013_auto_20180708_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
