# Generated by Django 2.0.6 on 2018-07-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0014_customers_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
