# Generated by Django 2.0.6 on 2018-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0015_orders_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
