# Generated by Django 2.0.6 on 2018-07-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0016_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity_100',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity_125',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity_150',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity_200',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity_60',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity_75',
        ),
        migrations.AddField(
            model_name='orders',
            name='order',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
