# Generated by Django 2.0.6 on 2018-07-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0018_orders_money_receive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='money_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
