# Generated by Django 2.0.6 on 2018-07-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0019_auto_20180720_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_boy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
