# Generated by Django 2.0.6 on 2018-12-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0020_auto_20180720_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sub_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
